apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sisyphus-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"

    nginx.ingress.kubernetes.io/priority: "200"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sisyphus.garnaudov.com
      secretName: sisyphus-tls
  rules:
    - host: sisyphus.garnaudov.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sisyphus-api-service
                port:
                  number: 80
