apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: default
spec:
  encryptedData:
    db-url: AgAWLVczdglyuTw07A3dRMIrb1akUiuU6jmudvH2lAfYalzVaWR+acmPiZns8RLyOhjfUobwkKcCiQ8vqzafm7G75wN9ICpTPfmXRKjJXq4+SQ0xHgix+OhzSw+cCfZoFgp6QRTFU8ZqjvdYKJXcymKk4uD1OA/bykgNZ6/d+BeOLcsfgFiC+lYG8Ai38St3zo0D2cbHZahMx+G4yhT5plEs6tH2eKIeNEJyeIIl8624b1JOg+5ooCBQjZX/YePEfi6I8gUYANSCvIacRuHQFavore4Rd5ERf73RpfY5DrLL551Nye1JBLuJiGFvzVLVaTSd9Q5aqCmHKhgcBkTCwCo4p/6p5kJp5rf2G9JywWqtRT/pU+G6w2m0blJTmNUidByo68jlT+at3pVBPm6dHBgqVD8tTsEXqna6foRU/RHauutFxi6maB/PZHPkFsoKLhvvbCB608YwdLEbTdRKLw2PR0YU2OmRl9dh0rNcx6VaSUuMZGbk7UhQYd0E71hLPaeb9XQrWOLCxcSWqBzSFD7P4Wp0PAh04lfvW+Gt4XzYkzdVhfzDmk2jp2idcsGBfYcUYomUyJMsxn1gvIFUl4GB2j1c/nAVF8wMYHydz903vE3H2RS60x0KKEONHxqu+uRFhgDj+XDz0o2q44rfsMu3a6Hpk/d6r27cPOT+BrgpX2M3fx6PjNKHbOJiIPGi/F+XDH4ai+G/NNUpsm9xoOCVGSSJnqLDiE33fnh2RWHCnekRNd6IuZYGf0L1vuhXPTDZBomqY4vC1GbLskGIg65R9rviq1LLwSIZEM2WYCSdgZmtBvoZFRVQ/qpamIkwJ/dkPScYp7RS7PD9U9Ifa5ftD9Ddqw5EIrgn6aXjr6Wkyp/Kzr1Z/O0JBAeap2naktej
    jwt-secret: AgBZDu9jbng5pEknPsgeRmp8Q5CFH61Bk9RZlvg4bGzKFUnDRaRKmDWmAt6B+D+97zL1V2P3G9OgGpCCvnqxtnKJkHNTNjilEAS0/lVProhIqBk449MLX3ltB/msgxut8NE4LaT0lYVCel5EYXXyPjebGhYEVxf6SP8EUWqBPwXN5np8Hp7JN5VX8siM53wig8zmxa8UYMFn4ggVE1NeNwPiyzupYpiI4AzJwd9eLZX+hBhWfGd36Uk8OUNycxtGP8YhIiu0528J0W3sXdbLddaJpeY+8knngWxxI9/btTpOvKAs4srE2CSkvpJKQYekguVwN7ghG7PVkFc46M0Ln9AzfgX4xEaC3dDm1BcdZVez/KiWgaiZLIyT+tqz5DlmbFiGv9YmOcwuH7A4Nr9CKFbH1AkJUK55rvJrlrvXupmkqkUYhZ5vBzGCg0JXaNOApdN7bPEOvdcSvEcEO3se6tX0VSYb7WJfx2wixjMyp1IncbQ9Lhy9jyI9tjjpYH3hYcDX3Om339n9aUF/gbCSxmjdnBEHWTbGZ0DVhf8cEThKGK9HI/xVVKO2iDyXhFzc2OClFweadoWYZmPWlSOgg8SSQmjD9tXC9HNRxQONfdGm9oh7vpk4UpfaycG6Fx7MKdID2OdAz10Tvroeb3qZ6rJOB3g0NwBCx29ifD3j0z2ePR1XvMZuJNvyRuTTZG8TqnE8yk+dVl6Z3GQICOzvQFog9CEHRwb5zpdyrh45qTk670qVQ3OEJMAtUrW+/4o58cvxlNFeHqNXP71obY+wytmKAw==
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: default
    type: Opaque

