name: Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - kubernetes/sisyphus-client/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save sisyphus-cluster

      - name: Validate manifests
        run: kubectl apply --dry-run=client -f kubernetes/sisyphus-client

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f kubernetes/sisyphus-client
